version: '3.9'
services:
  db:
    container_name: supermarkt-db
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: supermarkt
  func:
    container_name: supermarkt-func
    build: ./scrape
    depends_on:
      - db
    environment:
      - CONN_URL=postgres://postgresuser:postgrespwd@supermarkt-db:5432/supermarkt
  api:
    container_name: supermarkt-api
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
      - func
    environment:
      - CONN_URL=postgres://postgresuser:postgrespwd@supermarkt-db:5432/supermarkt
      - SCRAPER_URL=http://supermarkt-func:7071
      - API_SECRET=yoursecretstring
      - TOKEN_HOUR_LIFESPAN=1