version: '3.9'
services:
  storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    hostname: azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
  db:
    container_name: supermarkt-db
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: supermarkt
    ports:
      - 5432:5432
  func:
    container_name: supermarkt-func
    build: ./scrape
    ports:
      - 7071:7071
    depends_on:
      - storage
      - db