version: '3.9'
services:
  db:
    container_name: supermarkt-db
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: supermarkt
    ports:
      - 5432:5432
  func:
    container_name: supermarkt-func
    build: ./scrape
    ports:
      - 7071:7071
    depends_on:
      - db
    environment:
      - CONN_URL=postgres://postgresuser:postgrespwd@supermarkt-db:5432/supermarkt
  api:
    container_name: supermarkt-api
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db